name : comment on new issue

on:
 issues:
   types: [opened]
   
jobs:
  comment-with-api:
   runs-on: ubuntu-latest
   steps: 
    - name: "dump github context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
